# Generated by Django 5.1.7 on 2025-04-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='closed',
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Closed', 'Closed')], default='Pending', max_length=10),
        ),
    ]
